Update sgplot package to use analysis function colour palettes
best-practice-and-impact/afcharts pull request #1
Opened 2024-07-23 14:28 UTC by Olivia-Box-Power

2024-08-01 14:38 UTC, alice-hannah requested changes
Hi Olivia,

Thanks for being patient whilst I found the time to look over this. I've added a few individual comments / suggestions and also have a few general ones:

* I didn't expect you to remove the SG colour palettes completely. I thought these would be retained and the colour functions would be amended to use the `af` palettes by default, but keeping the `sg` palettes as an option. Could these be kept please?

* To update links to the GitHub pages site you could do a Find in Files search to replace `ScotGovAnalysis.github.io/sgplot` with `best-practice-and-impact.github.io/afcharts`.

* There's mixed use of 'UK Government', 'UK Government Analysis Function' and 'Government Analysis Function'. I had a look at their website and I think they use 'Government Analysis Function'. Could we amend this throughout for consistency?

* I noticed the sgplot hex logo is still included and displayed in the README. I think this is fine if it makes it easier to replace when we have one for afcharts.

Happy to have another quick review to approve once you've made these changes.

Thanks,
Alice

2024-08-01 15:07 UTC, Olivia-Box-Power commented on DESCRIPTION
> +    person("Olivia", "Box Power", , "Olivia.BoxPower@dhsc.gov.uk", role = "ctb")
Thanks, sounds good.

2024-08-01 15:08 UTC, Olivia-Box-Power commented on NEWS.md
> +First release of package based on sgplot.
Good spot!

2024-08-01 15:09 UTC, Olivia-Box-Power commented on _pkgdown.yml
> +  Government Analysis Function:
Thanks. I'll add my details.

2024-08-01 15:11 UTC, Olivia-Box-Power commented on README.Rmd
> +Titles, subtitles and captions have been embedded in these example charts for demonstration purposes. However, for accessibility reasons, it is usually preferable to provide titles in the body of the
Nope. Apologies, I think that was deleted by mistake. I'll add back in.

2024-08-01 15:14 UTC, Olivia-Box-Power commented on vignettes/cookbook/_acknowledgments.Rmd
> +The afcharts package is based on the [sgplot](https://scotgovanalysis.github.io/sgplot/index.html) package, written by Alice Hannah.
Good spot. I'll add this to the readme.

2024-08-02 08:38 UTC, Olivia-Box-Power commented on _pkgdown.yml
> +  Government Analysis Function:
commit 1ea971ab

2024-08-02 08:47 UTC, Olivia-Box-Power commented on README.Rmd
> +Titles, subtitles and captions have been embedded in these example charts for demonstration purposes. However, for accessibility reasons, it is usually preferable to provide titles in the body of the
Commit 06539d17

2024-08-02 10:23 UTC, Olivia-Box-Power commented on R/scale_colour_continuous_af.R
> +    af = af_colour_palettes
Fixed in commit c35edff5

2024-08-02 10:43 UTC, Olivia-Box-Power commented
Made name of Government analysis function consistent in commit 9d70339c

2024-08-02 11:07 UTC, Olivia-Box-Power commented on vignettes/cookbook/_acknowledgments.Rmd
> +The afcharts package is based on the [sgplot](https://scotgovanalysis.github.io/sgplot/index.html) package, written by Alice Hannah.
Commit 1c03ecca

2024-08-02 11:14 UTC, Olivia-Box-Power commented on vignettes/cookbook/_colour-palettes.Rmd
>  To use an Analysis Function palette, set `palette_type = "af"` when using any of the `scale_` [colour functions](https://scotgovanalysis.github.io/sgplot/reference/index.html#colours).
Remove in commit 47b358f3

2024-08-06 09:03 UTC, alice-hannah approved these changes

2024-08-06 09:04 UTC, alice-hannah commented
Thanks for making those changes 👍 I've approved the PR now so you can merge when you're ready. We can come back to including/excluding the SG palettes after we've discussed with the wider group. Thanks 😃

2024-08-06 09:54 UTC, merged